import {Position} from "reactflow";

export const decisionNodeConfig = (id) => ({
  title: "Decision",
  description: "Conditional logic - route based on yes/no decision",
  color: "decision",
  handles: [
    {
      id: `${id}-input`,
      type: "target",
      position: Position.Top,
      label: "Input",
    },
    {
      id: `${id}-yes`,
      type: "source",
      position: Position.Bottom,
      label: "Yes",
    },
    {
      id: `${id}-no`,
      type: "source",
      position: Position.Right,
      label: "No",
    },
  ],
  fields: [
    {
      key: "inputValue",
      label: "Value to Check",
      type: "text",
      placeholder: "Enter value or connect from previous node",
      defaultValue: "",
    },
    {
      key: "conditionMode",
      label: "Condition Mode",
      type: "select",
      options: ["Simple Comparison", "Custom Expression"],
      defaultValue: "Simple Comparison",
    },
    {
      key: "operator",
      label: "Operator",
      type: "select",
      options: [
        {value: ">", label: "Greater than (>)"},
        {value: ">=", label: "Greater or equal (>=)"},
        {value: "<", label: "Less than (<)"},
        {value: "<=", label: "Less or equal (<=)"},
        {value: "==", label: "Equals (==)"},
        {value: "===", label: "Strictly equals (===)"},
        {value: "!=", label: "Not equals (!=)"},
        {value: "!==", label: "Not strictly equals (!==)"},
        {value: "contains", label: "Contains"},
        {value: "startsWith", label: "Starts with"},
        {value: "endsWith", label: "Ends with"},
        {value: "isEmpty", label: "Is empty"},
        {value: "isNull", label: "Is null"},
      ],
      defaultValue: ">",
      conditional: true,
      showWhen: (fieldValues) => fieldValues.conditionMode === "Simple Comparison",
    },
    {
      key: "compareValue",
      label: "Compare With",
      type: "text",
      placeholder: "Enter comparison value",
      defaultValue: "",
      conditional: true,
      showWhen: (fieldValues) => fieldValues.conditionMode === "Simple Comparison" && !["isEmpty", "isNull", "isTruthy", "isFalsy"].includes(fieldValues.operator),
    },
    {
      key: "customExpression",
      label: "Expression",
      type: "textarea",
      placeholder: 'e.g., x > 10 && x < 100\nOr: x % 2 !== 0 (is odd)\nOr: x.includes("hello")',
      rows: 4,
      defaultValue: "",
      conditional: true,
      showWhen: (fieldValues) => fieldValues.conditionMode === "Custom Expression",
    },
  ],
});
